name: Coverage
on:
  pull_request:
    branches:
      - main

env:
  python-version: 3.13

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    if: github.actor != 'renovate[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Python ${{ env.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}

      - name: Install Dependencies
        run: uv sync --locked

      - name: Run Coverage
        id: coverage
        run: |
          uv run coverage run --source canary_cd -m pytest

      - name: Create Coverage Report
        id: report
        run: |
          {
            echo 'STDOUT<<EOF'
            uv run coverage report -m --skip-covered --format=markdown
            echo EOF
          } >> "$GITHUB_OUTPUT"
          {
            echo 'TOTAL<<EOF'
            uv run coverage report -m --format=total
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const coverageTotal = ${{ steps.report.outputs.total }}; 
            let coverageColor = 'green';
            if (coverageTotal < 80) { coverageColor = 'yellow' };
            if (coverageTotal < 60) { coverageColor = 'orange' };
            if (coverageTotal < 50) { coverageColor = 'red' };
            
            const output = `### Coverage Results for Run \`${{ github.run_id }}\`

            ![Coverage](https://img.shields.io/badge/Coverage-${ coverageTotal }%25-${coverageColor})
            
            #### Coverage
            <details><summary>Coverage Results</summary>

            ${{ steps.report.outputs.stdout }}
            
            </details>
            `;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Coverage Results for Run')
            })
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
